name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: wisecow-deployment  # Replace with your Google Cloud Project ID
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate Docker
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t gcr.io/wisecow-deployment/wisecow-app:latest .

    - name: Push Docker image
      run: docker push gcr.io/wisecow-deployment/wisecow-app:latest

    - name: Deploy to GKE
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
